unstable_features = true
binop_separator = "Front"

wrap_comments = true
comment_width = 80
normalize_comments = true

format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_doc_attributes = true

format_strings = true

reorder_impl_items = true

space_after_colon = true
spaces_around_ranges = false

trailing_semicolon = true
